# Generated by Django 5.0.6 on 2026-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=50, unique=True)),
                ('page_label', models.CharField(max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=120)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('og_title', models.CharField(blank=True, max_length=120)),
                ('og_description', models.TextField(blank=True, max_length=300)),
                ('og_image', models.URLField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
            },
        ),
    ]
