# Generated by Django 5.0.6 on 2026-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Springboard Indian School', max_length=200)),
                ('tagline', models.CharField(default="Where Every Child's Journey Begins", max_length=300)),
                ('address', models.TextField(default='Survey No. 123, Kondapur, Hyderabad, Telangana 500084')),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_admissions', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('admission_open', models.BooleanField(default=True)),
                ('seats_available', models.CharField(default='12', max_length=10)),
                ('announcement_bar', models.CharField(blank=True, max_length=400)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('academic_year', models.CharField(default='2026-27', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
