# Generated by Django 5.0.6 on 2026-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='geo_placename',
            field=models.CharField(blank=True, help_text='e.g. Hyderabad', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='geo_region',
            field=models.CharField(blank=True, help_text='e.g. IN-TG for Telangana, India', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.URLField(blank=True),
        ),
    ]
